modLoader="javafml"
loaderVersion="[36,)"

[[mods]]
modId="pixelmonprowlers"
version="1.0"
displayName="Prowlers"
displayURL="https://github.com/EnzoMartini3"
credits="https://github.com/EnzoMartini3"
authors="https://github.com/EnzoMartini3"
description='''
Conserta o gamedesign assombroso da Gamefreak.
'''

[[dependencies.pixelmonprowlers]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.pixelmonprowlers]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"


[[dependencies.pixelmonprowlers]]
modId="pixelmon"
mandatory=true
versionRange="[9.1.12,)"
ordering="NONE"
side="BOTH"
